name: Auto-merge for Codex and approved PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Check if PR is from Codex or approved
        id: check_conditions
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          
          # Check if author is Codex or similar bot
          if [[ "$PR_AUTHOR" == *"codex"* ]] || [[ "$PR_AUTHOR" == *"bot"* ]] || [[ "$PR_AUTHOR" == *"dependabot"* ]]; then
            echo "auto_merge=true" >> $GITHUB_OUTPUT
            echo "reason=bot_author" >> $GITHUB_OUTPUT
          else
            # Check if PR has been approved
            APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[] | select(.state=="APPROVED")] | length')
            if [[ $APPROVALS -gt 0 ]]; then
              echo "auto_merge=true" >> $GITHUB_OUTPUT
              echo "reason=approved" >> $GITHUB_OUTPUT
            else
              echo "auto_merge=false" >> $GITHUB_OUTPUT
              echo "reason=no_approval" >> $GITHUB_OUTPUT
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        if: steps.check_conditions.outputs.auto_merge == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
          echo "✅ Auto-merge enabled for PR #${{ github.event.pull_request.number }} (reason: ${{ steps.check_conditions.outputs.reason }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment for auto-merge
        if: steps.check_conditions.outputs.auto_merge == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "🤖 Auto-merge enabled! This PR will be merged automatically once all checks pass."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-approve-bots:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false && (contains(github.event.pull_request.user.login, 'codex') || contains(github.event.pull_request.user.login, 'bot') || contains(github.event.pull_request.user.login, 'dependabot'))
    steps:
      - name: Auto-approve bot PRs
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --body "✅ Auto-approved: Trusted bot contribution"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}