[build]
  command = "npm run build"
  publish = "dist"
  # זמני: דילוג על כל דיפלוי עד שנשחרר
  ignore = "exit 0"

[build.environment]
  NODE_VERSION = "20"
  SUPABASE_SERVICE_ROLE_KEY = ""

[functions]
  node_bundler = "esbuild"

# Headers for better security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.supabase.co wss://*.supabase.co"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
